### ISSUE TITLE
Sed command is not compatible for OSX in kubernetes-client/gen/openapi/haskell.sh

### ISSUE THREAD

**Issue by irvifa** [kubernetes-client/gen#116]
This is related to https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux where OSX don't support `-i` flag in the script, I think there can be 2 different approach:

1. First improve the docs so that those who wants to use the script aware that we are using sed to override the value on the `cabal` file.
2. Give and additional if else condition for this script.

**Comment by prksu** [comment]
This has been notified in kubernetes contributors devel https://github.com/kubernetes/community/blob/master/contributors/devel/development.md#building-kubernetes-on-a-local-osshell-environment

since the contributing guide in this repo also refered to [Kubernetes contributor guide](https://github.com/kubernetes/community/blob/master/contributors/guide/README.md) so I don't think it needs to be added to this repo docs anymore

**Comment by irvifa** [comment]
Thanks i'll closing this issue then. I missed the details about it.
