### ISSUE TITLE
kubernetes-client/gen/openapi/python.sh - 'no such file or directory' exec error

### ISSUE THREAD

**Issue by marie-yau** [kubernetes-client/gen#83]
An error occurred when executing kubernetes-client/gen/openapi/python.sh

Following the instructions under the “Generating a client” 
( https://github.com/kubernetes-client/gen ):

${CLIENT_LANGUAGE}.sh OUTPUT_DIR SETTING_FILE

Below is an example run:

/root/kubernetes/gen/openapi/python.sh /root/output_client/kubernetes /root/kubernetes/python/settings

The /root/kubernetes/python/settings files is as follows:

export KUBERNETES_BRANCH="master" 
export CLIENT_VERSION="8.0.0b1"
 export PACKAGE_NAME="kubernetes"

The stdout from the above run is shown below, revealing an execution find error in the last line: 
...
---Done. 
--- Patching generated code ...
find: '/root/output_client/kubernetes/client/': No such file or directory
...

I will submitt a PR to the kubernetes-client/gen repo to remedy the execution error above.

The fix involved modifying:  /root/kubernetes/gen/openapi/python.sh

**Comment by tomplus** [comment]
Your settings file should have ` export PACKAGE_NAME="client"`, because the generated code lands as the sub-directory `/client` within the package: https://github.com/kubernetes-client/python/tree/master/kubernetes/client

BTW, if you need to regenerate client you can use the script https://github.com/kubernetes-client/python/blob/master/scripts/update-client.sh which does the job.
